
SHOW INDEX FROM TRANSACTION_BILL;


SELECT SUM(ITEM_PRICE) 
FROM TRANSACTION_BILL A
JOIN TRANSACTION B
ON A.TRANSACTION_NO=B.TRANSACTION_NO
WHERE  CUSTOMER_ID='1' AND B.TRANSACTION_DATE BETWEEN DATE_SUB(NOW(), INTERVAL 5 YEAR) AND NOW()
GROUP BY CUSTOMER_ID;



CREATE INDEX CUST_INDEX ON TRANSACTION_BILL(CUSTOMER_ID);



SELECT SUM(ITEM_PRICE) 
FROM TRANSACTION_BILL A
JOIN TRANSACTION B
ON A.TRANSACTION_NO=B.TRANSACTION_NO
WHERE  CUSTOMER_ID='1' AND B.TRANSACTION_DATE BETWEEN DATE_SUB(NOW(), INTERVAL 5 YEAR) AND NOW()
GROUP BY CUSTOMER_ID;



TRUNCATE TABLE TRANSACTION;

TRUNCATE TABLE TRANSACTION_BILL;



DROP INDEX  CUST_INDEX ON TRANSACTION_BILL;






